export const inputSetSeq = [
    {name: ['waitToPressSpace','pressSpaceKey', 'upKey', 'threeSecStateUnchanged'],
        duration: '5000'},
    {name: ['waitToPressSpace','pressSpaceKey', 'downKey', 'threeSecStateUnchanged'],
        duration: '5000'},
    {name: ['waitToPressSpace','pressSpaceKey', 'followBall', 'threeSecStateUnchanged'],
        duration: '5000'},
    {name: ['waitToPressSpace','pressSpaceKey', 'followBall', 'threeSecStateUnchanged'],
        duration: '5000'},
    {name: ['waitToPressSpace','pressSpaceKey', 'followBall', 'threeSecStateUnchanged'],
        duration: '5000'},
    {name: ['waitToPressSpace','pressSpaceKey', 'followBall', 'threeSecStateUnchanged'],
        duration: '5000'},
    {name: ['waitToPressSpace','pressSpaceKey', 'followBall', 'threeSecStateUnchanged'],
        duration: '5000'},
    {name: ['waitToPressSpace','pressSpaceKey', 'followBall', 'threeSecStateUnchanged'],
        duration: '5000'},
    {name: ['waitToPressSpace','pressSpaceKey', 'followBall', 'threeSecStateUnchanged'],
        duration: '5000'},
    {name: ['waitToPressSpace','pressSpaceKey', 'followBall', 'threeSecStateUnchanged'],
        duration: '5000'},
    {name: ['waitToPressSpace','pressSpaceKey', 'followBall', 'threeSecStateUnchanged'],
        duration: '5000'},
    {name: ['waitToPressSpace','pressSpaceKey', 'followBall', 'threeSecStateUnchanged'],
        duration: '5000'},
    {name: ['waitToPressSpace','pressSpaceKey', 'followBall', 'threeSecStateUnchanged'],
        duration: '5000'},
    {name: ['waitToPressSpace','pressSpaceKey', 'followBall', 'threeSecStateUnchanged'],
        duration: '5000'},
];
